solved_background_color: 
  default: "#eefbdc"
  description: "CSS background color, when using a hex be sure to include the #"

solved_background_color_dark: 
  default: "#242d19"
  description: "CSS background color when dark mode is enabled, when using a hex be sure to include the #"

solved_translation: 
  default: "solution"
  description: "This is a word from the title text in the solved topic status, which is being used to target with CSS"